# Generated by Django 4.2.28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_user_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='minimum_sanitation_grade',
            field=models.CharField(
                blank=True,
                choices=[
                    ('', 'Not Graded'),
                    ('N', 'N'),
                    ('A', 'A'),
                    ('Z', 'Z'),
                    ('B', 'B'),
                    ('C', 'C'),
                ],
                default='C',
                max_length=10,
            ),
        ),
    ]
