# Generated by Django 4.2.28 on 2026-03-28 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_venuemanagerprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpreference",
            name="minimum_sanitation_grade",
            field=models.CharField(
                blank=True,
                choices=[
                    ("P", "P"),
                    ("N", "N"),
                    ("A", "A"),
                    ("Z", "Z"),
                    ("B", "B"),
                    ("C", "C"),
                ],
                default="A",
                max_length=10,
            ),
        ),
    ]
