# Generated by Django 4.2.28 on 2026-04-14 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_seed_default_admin_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="photo_url",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
