# Generated by Django 4.2.28 on 2026-04-16 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_user_photo_url"),
        ("accounts", "0011_userpreference_price_range"),
    ]

    operations = []
