# Generated by Django 4.2.28 on 2026-04-22 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_merge_legacy_jewish_kosher_dietary_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, default="", max_length=500),
        ),
    ]
