# Generated by Django 4.2.28 on 2026-03-27 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_userpreference_minimum_sanitation_grade"),
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupConstraint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "minimum_sanitation_grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("P", "P"),
                            ("N", "N"),
                            ("A", "A"),
                            ("Z", "Z"),
                            ("B", "B"),
                            ("C", "C"),
                        ],
                        default="A",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cuisine_types",
                    models.ManyToManyField(
                        blank=True,
                        related_name="group_constraints",
                        to="accounts.cuisinetype",
                    ),
                ),
                (
                    "dietary_tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="group_constraints",
                        to="accounts.dietarytag",
                    ),
                ),
                (
                    "food_type_tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="group_constraints",
                        to="accounts.foodtypetag",
                    ),
                ),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="constraints",
                        to="groups.group",
                    ),
                ),
            ],
        ),
    ]
