# Generated by Django 4.2.28 on 2026-03-28 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0002_swipeevent_swipe"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="swipe",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="swipe",
            constraint=models.UniqueConstraint(
                fields=("event", "user", "venue"),
                name="unique_swipe_per_user_venue_event",
            ),
        ),
    ]
