# Generated by Django 4.2.28 on 2026-03-30 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0002_groupconstraint"),
        ("groups", "0003_alter_swipe_unique_together_and_more"),
    ]

    operations = []
