# Generated by Django 4.2.28 on 2026-04-04 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0005_swipeevent_borough_neighborhood"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupconstraint",
            name="price_range",
            field=models.CharField(
                blank=True,
                choices=[("$", "$"), ("$$", "$$"), ("$$$", "$$$"), ("$$$$", "$$$$")],
                max_length=4,
            ),
        ),
    ]
