# Generated by Django 4.2.28 on 2026-04-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0008_swipesessionnotification_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="join_code",
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
