# Generated by Django 4.2.28 on 2026-04-17 02:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("groups", "0009_group_join_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="swipeevent",
            name="completed_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="completed_swipe_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
