# Generated by Django 4.2.28 on 2026-04-17 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0010_swipeevent_completed_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="swipeevent",
            name="venue_limit",
            field=models.IntegerField(default=10),
        ),
    ]
